//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VDSI_EmCarPooling_DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VDSI_CARPEntities : DbContext
    {
        public VDSI_CARPEntities()
            : base("name=VDSI_CARPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<LOGIN> LOGINs { get; set; }
        public DbSet<POOLINGREQUEST> POOLINGREQUESTs { get; set; }
        public DbSet<CARREGDETAIL> CARREGDETAILS { get; set; }
    }
}
