//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VDSI_EmCarPooling_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGIN
    {
        public int Id { get; set; }
        public string EmpId { get; set; }
        public string EmpName { get; set; }
        public string Password { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
