//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VDSI_EmCarPooling_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class POOLINGREQUEST
    {
        public int Id { get; set; }
        public string ReqEmpId { get; set; }
        public string OwnerEmpId { get; set; }
        public Nullable<int> Seats { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
